# Generated by Django 3.2.22 on 2024-02-09 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_rename_type_name_accounttype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckboxOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FromTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('mail_id', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(blank=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.accounttype')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.branch')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.districts')),
                ('meterials_provide', models.ManyToManyField(to='credentials.CheckboxOptions')),
            ],
        ),
    ]
