# Generated by Django 3.2.22 on 2024-02-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_checkboxoptions_fromtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkboxoptions',
            name='name',
            field=models.CharField(choices=[('credit card', 'credit card'), ('debit card', 'debit card')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fromtable',
            name='meterials_provide',
            field=models.ManyToManyField(blank=True, to='credentials.CheckboxOptions'),
        ),
    ]
