# Generated by Django 3.2.22 on 2024-02-10 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_auto_20240210_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fromtable',
            old_name='meterials_provide',
            new_name='choices',
        ),
    ]
