# Generated by Django 3.2.22 on 2024-02-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0005_rename_meterials_provide_fromtable_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkboxoptions',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
